
package org.openup.aduana.mic.conexion.produccion;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ws_MensManifiesto", targetNamespace = "www.aduanas.gub.uy/DAE", wsdlLocation = "file:/home/raul/Desarrollo/IDE/Eclipse/workspace/OpenUpAduana/src/org/openup/aduana/miscelanea/wsdl_MIC_produccion.xsd")
public class WsMensManifiesto
    extends Service
{

    private final static URL WSMENSMANIFIESTO_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.openup.aduana.mic.conexion.produccion.WsMensManifiesto.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.openup.aduana.mic.conexion.produccion.WsMensManifiesto.class.getResource(".");
            url = new URL(baseUrl, "file:/home/raul/Desarrollo/IDE/Eclipse/workspace/OpenUpAduana/src/org/openup/aduana/miscelanea/wsdl_MIC_produccion.xsd");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/home/raul/Desarrollo/IDE/Eclipse/workspace/OpenUpAduana/src/org/openup/aduana/miscelanea/wsdl_MIC_produccion.xsd', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WSMENSMANIFIESTO_WSDL_LOCATION = url;
    }

    public WsMensManifiesto(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsMensManifiesto() {
        super(WSMENSMANIFIESTO_WSDL_LOCATION, new QName("www.aduanas.gub.uy/DAE", "ws_MensManifiesto"));
    }

    /**
     * 
     * @return
     *     returns WsMensManifiestoSoapPort
     */
    @WebEndpoint(name = "ws_MensManifiestoSoapPort")
    public WsMensManifiestoSoapPort getWsMensManifiestoSoapPort() {
        return super.getPort(new QName("www.aduanas.gub.uy/DAE", "ws_MensManifiestoSoapPort"), WsMensManifiestoSoapPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsMensManifiestoSoapPort
     */
    @WebEndpoint(name = "ws_MensManifiestoSoapPort")
    public WsMensManifiestoSoapPort getWsMensManifiestoSoapPort(WebServiceFeature... features) {
        return super.getPort(new QName("www.aduanas.gub.uy/DAE", "ws_MensManifiestoSoapPort"), WsMensManifiestoSoapPort.class, features);
    }

}
