//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.02 at 06:10:13 PM UYST 
//


package org.openup.aduana.dua.dto;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.openup.aduana.dua.dto package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.openup.aduana.dua.dto
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link WSDUASDT.ENTRADASSTK }
     * 
     */
    public WSDUASDT.ENTRADASSTK createWSDUASDTENTRADASSTK() {
        return new WSDUASDT.ENTRADASSTK();
    }

    /**
     * Create an instance of {@link WSDUASDT.FACTURAS }
     * 
     */
    public WSDUASDT.FACTURAS createWSDUASDTFACTURAS() {
        return new WSDUASDT.FACTURAS();
    }

    /**
     * Create an instance of {@link WSDUASDT.CONTENEDORES }
     * 
     */
    public WSDUASDT.CONTENEDORES createWSDUASDTCONTENEDORES() {
        return new WSDUASDT.CONTENEDORES();
    }

    /**
     * Create an instance of {@link ArrayOfWSDUASDTENTRADASTK }
     * 
     */
    public ArrayOfWSDUASDTENTRADASTK createArrayOfWSDUASDTENTRADASTK() {
        return new ArrayOfWSDUASDTENTRADASTK();
    }

    /**
     * Create an instance of {@link ArrayOfWSDUASDTFACTURA }
     * 
     */
    public ArrayOfWSDUASDTFACTURA createArrayOfWSDUASDTFACTURA() {
        return new ArrayOfWSDUASDTFACTURA();
    }

    /**
     * Create an instance of {@link ArrayOfWSDUASDTCONTENEDOR }
     * 
     */
    public ArrayOfWSDUASDTCONTENEDOR createArrayOfWSDUASDTCONTENEDOR() {
        return new ArrayOfWSDUASDTCONTENEDOR();
    }

    /**
     * Create an instance of {@link WSDUAExecuteResponse }
     * 
     */
    public WSDUAExecuteResponse createWSDUAExecuteResponse() {
        return new WSDUAExecuteResponse();
    }

    /**
     * Create an instance of {@link WSDUAExecute }
     * 
     */
    public WSDUAExecute createWSDUAExecute() {
        return new WSDUAExecute();
    }

    /**
     * Create an instance of {@link WSDUASDTENTRADASTK }
     * 
     */
    public WSDUASDTENTRADASTK createWSDUASDTENTRADASTK() {
        return new WSDUASDTENTRADASTK();
    }

    /**
     * Create an instance of {@link WSDUASDT.MOVIMIENTOS }
     * 
     */
    public WSDUASDT.MOVIMIENTOS createWSDUASDTMOVIMIENTOS() {
        return new WSDUASDT.MOVIMIENTOS();
    }

    /**
     * Create an instance of {@link WSDUASDTDOCUMENTO }
     * 
     */
    public WSDUASDTDOCUMENTO createWSDUASDTDOCUMENTO() {
        return new WSDUASDTDOCUMENTO();
    }

    /**
     * Create an instance of {@link WSDUASDTASOC }
     * 
     */
    public WSDUASDTASOC createWSDUASDTASOC() {
        return new WSDUASDTASOC();
    }

    /**
     * Create an instance of {@link WSDUASDTCORRELACIONADO }
     * 
     */
    public WSDUASDTCORRELACIONADO createWSDUASDTCORRELACIONADO() {
        return new WSDUASDTCORRELACIONADO();
    }

    /**
     * Create an instance of {@link WSDUASDT.ITEMS }
     * 
     */
    public WSDUASDT.ITEMS createWSDUASDTITEMS() {
        return new WSDUASDT.ITEMS();
    }

    /**
     * Create an instance of {@link ArrayOfWSDUASDTDOCUMENTO }
     * 
     */
    public ArrayOfWSDUASDTDOCUMENTO createArrayOfWSDUASDTDOCUMENTO() {
        return new ArrayOfWSDUASDTDOCUMENTO();
    }

    /**
     * Create an instance of {@link ArrayOfWSDUASDTASOC }
     * 
     */
    public ArrayOfWSDUASDTASOC createArrayOfWSDUASDTASOC() {
        return new ArrayOfWSDUASDTASOC();
    }

    /**
     * Create an instance of {@link WSDUASDTITEM }
     * 
     */
    public WSDUASDTITEM createWSDUASDTITEM() {
        return new WSDUASDTITEM();
    }

    /**
     * Create an instance of {@link ArrayOfWSDUASDTCORRELACIONADO }
     * 
     */
    public ArrayOfWSDUASDTCORRELACIONADO createArrayOfWSDUASDTCORRELACIONADO() {
        return new ArrayOfWSDUASDTCORRELACIONADO();
    }

    /**
     * Create an instance of {@link WSDUASDT.CORRELACIONADOS }
     * 
     */
    public WSDUASDT.CORRELACIONADOS createWSDUASDTCORRELACIONADOS() {
        return new WSDUASDT.CORRELACIONADOS();
    }

    /**
     * Create an instance of {@link WSDUASDT }
     * 
     */
    public WSDUASDT createWSDUASDT() {
        return new WSDUASDT();
    }

    /**
     * Create an instance of {@link WSDUASDTCONTENEDOR }
     * 
     */
    public WSDUASDTCONTENEDOR createWSDUASDTCONTENEDOR() {
        return new WSDUASDTCONTENEDOR();
    }

    /**
     * Create an instance of {@link ArrayOfWSDUASDTMOVIMIENTO }
     * 
     */
    public ArrayOfWSDUASDTMOVIMIENTO createArrayOfWSDUASDTMOVIMIENTO() {
        return new ArrayOfWSDUASDTMOVIMIENTO();
    }

    /**
     * Create an instance of {@link WSDUASDT.ASOCIACIONES }
     * 
     */
    public WSDUASDT.ASOCIACIONES createWSDUASDTASOCIACIONES() {
        return new WSDUASDT.ASOCIACIONES();
    }

    /**
     * Create an instance of {@link WSDUASDTFACTURA }
     * 
     */
    public WSDUASDTFACTURA createWSDUASDTFACTURA() {
        return new WSDUASDTFACTURA();
    }

    /**
     * Create an instance of {@link ArrayOfWSDUASDTITEM }
     * 
     */
    public ArrayOfWSDUASDTITEM createArrayOfWSDUASDTITEM() {
        return new ArrayOfWSDUASDTITEM();
    }

    /**
     * Create an instance of {@link WSDUASDTMOVIMIENTO }
     * 
     */
    public WSDUASDTMOVIMIENTO createWSDUASDTMOVIMIENTO() {
        return new WSDUASDTMOVIMIENTO();
    }

    /**
     * Create an instance of {@link WSDUASDT.DOCUMENTOS }
     * 
     */
    public WSDUASDT.DOCUMENTOS createWSDUASDTDOCUMENTOS() {
        return new WSDUASDT.DOCUMENTOS();
    }

}
