//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.02 at 06:10:13 PM UYST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "www.aduanas.gub.uy/wsduasdt", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.openup.aduana.dua.dto;
