//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.02 at 06:10:13 PM UYST 
//


package org.openup.aduana.dua.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WSDUASDT.CORRELACIONADO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WSDUASDT.CORRELACIONADO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CODI_ADUAN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ANO_PRESE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NUME_CORRE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CODI_ALMA" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WSDUASDT.CORRELACIONADO", propOrder = {
    "codiaduan",
    "anoprese",
    "numecorre",
    "codialma"
})
public class WSDUASDTCORRELACIONADO {

    @XmlElement(name = "CODI_ADUAN", required = true)
    protected String codiaduan;
    @XmlElement(name = "ANO_PRESE", required = true)
    protected String anoprese;
    @XmlElement(name = "NUME_CORRE", required = true)
    protected String numecorre;
    @XmlElement(name = "CODI_ALMA", required = true)
    protected String codialma;

    /**
     * Gets the value of the codiaduan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCODIADUAN() {
        return codiaduan;
    }

    /**
     * Sets the value of the codiaduan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCODIADUAN(String value) {
        this.codiaduan = value;
    }

    /**
     * Gets the value of the anoprese property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getANOPRESE() {
        return anoprese;
    }

    /**
     * Sets the value of the anoprese property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setANOPRESE(String value) {
        this.anoprese = value;
    }

    /**
     * Gets the value of the numecorre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNUMECORRE() {
        return numecorre;
    }

    /**
     * Sets the value of the numecorre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNUMECORRE(String value) {
        this.numecorre = value;
    }

    /**
     * Gets the value of the codialma property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCODIALMA() {
        return codialma;
    }

    /**
     * Sets the value of the codialma property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCODIALMA(String value) {
        this.codialma = value;
    }

}
