//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.02 at 06:10:13 PM UYST 
//


package org.openup.aduana.dua.dto;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WSDUASDT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WSDUASDT">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CODI_ADUAN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ANO_PRESE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NUME_CORRE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CODI_ALMA" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ESTADO" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DESP_URGE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CODI_AGENT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DocumentoAgente" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TipoDocAgente" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NombreAgente" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NUME_ORDEN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CTIPODOC" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CDOCUMEN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="UNID_TRANS" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="VIA_TRANSP" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CODI_MONED" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="FECH_INGSI" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="HORA_INGSI" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ULTD_PAGO" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ID_MEDTRAN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TRVJID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="TIPO_TRAN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ASIG_EXTRA" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CODI_REGI" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ADUAINGEGR" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NOMB_IMPOR" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DIRE_IMPOR" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CODI_PAIS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PAIS_TRANS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="POLFECH_VENC" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="TOT_FACT" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="POLDOBS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="POLDEPDEST" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TIPO_AFORO" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FECH_VISREAL" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="DCLATRASAL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NDNA_TRACT" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="MATR_REMO" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MATR_SREM" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TDOCEMPTRA" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NDOCEMPTRA" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CALMDEST" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DCLATRALLE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ADUNUMORI" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TIPCAMVEN" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="TIPCAMCOM" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="POLFECAUTS" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="POLDUADIGI" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ITEMS">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ITEM" type="{www.aduanas.gub.uy/wsduasdt}WSDUASDT.ITEM" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ASOCIACIONES">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ASOC" type="{www.aduanas.gub.uy/wsduasdt}WSDUASDT.ASOC" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="CONTENEDORES">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CONTENEDOR" type="{www.aduanas.gub.uy/wsduasdt}WSDUASDT.CONTENEDOR" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="DOCUMENTOS">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DOCUMENTO" type="{www.aduanas.gub.uy/wsduasdt}WSDUASDT.DOCUMENTO" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="FACTURAS">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="FACTURA" type="{www.aduanas.gub.uy/wsduasdt}WSDUASDT.FACTURA" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ENTRADASSTK">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ENTRADASTK" type="{www.aduanas.gub.uy/wsduasdt}WSDUASDT.ENTRADASTK" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="MOVIMIENTOS">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="MOVIMIENTO" type="{www.aduanas.gub.uy/wsduasdt}WSDUASDT.MOVIMIENTO" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="CORRELACIONADOS">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CORRELACIONADO" type="{www.aduanas.gub.uy/wsduasdt}WSDUASDT.CORRELACIONADO" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WSDUASDT", propOrder = {
    "codiaduan",
    "anoprese",
    "numecorre",
    "codialma",
    "estado",
    "despurge",
    "codiagent",
    "documentoAgente",
    "tipoDocAgente",
    "nombreAgente",
    "numeorden",
    "ctipodoc",
    "cdocumen",
    "unidtrans",
    "viatransp",
    "codimoned",
    "fechingsi",
    "horaingsi",
    "ultdpago",
    "idmedtran",
    "trvjid",
    "tipotran",
    "asigextra",
    "codiregi",
    "aduaingegr",
    "nombimpor",
    "direimpor",
    "codipais",
    "paistrans",
    "polfechvenc",
    "totfact",
    "poldobs",
    "poldepdest",
    "tipoaforo",
    "fechvisreal",
    "dclatrasal",
    "ndnatract",
    "matrremo",
    "matrsrem",
    "tdocemptra",
    "ndocemptra",
    "calmdest",
    "dclatralle",
    "adunumori",
    "tipcamven",
    "tipcamcom",
    "polfecauts",
    "polduadigi",
    "items",
    "asociaciones",
    "contenedores",
    "documentos",
    "facturas",
    "entradasstk",
    "movimientos",
    "correlacionados"
})
@XmlRootElement(name = "DUA")
public class WSDUASDT {

    @XmlElement(name = "CODI_ADUAN", required = true)
    protected String codiaduan;
    @XmlElement(name = "ANO_PRESE", required = true)
    protected String anoprese;
    @XmlElement(name = "NUME_CORRE", required = true)
    protected String numecorre;
    @XmlElement(name = "CODI_ALMA", required = true)
    protected String codialma;
    @XmlElement(name = "ESTADO", required = true)
    protected String estado;
    @XmlElement(name = "DESP_URGE", required = true)
    protected String despurge;
    @XmlElement(name = "CODI_AGENT", required = true)
    protected String codiagent;
    @XmlElement(name = "DocumentoAgente", required = true)
    protected String documentoAgente;
    @XmlElement(name = "TipoDocAgente", required = true)
    protected String tipoDocAgente;
    @XmlElement(name = "NombreAgente", required = true)
    protected String nombreAgente;
    @XmlElement(name = "NUME_ORDEN", required = true)
    protected String numeorden;
    @XmlElement(name = "CTIPODOC", required = true)
    protected String ctipodoc;
    @XmlElement(name = "CDOCUMEN", required = true)
    protected String cdocumen;
    @XmlElement(name = "UNID_TRANS")
    protected byte unidtrans;
    @XmlElement(name = "VIA_TRANSP", required = true)
    protected String viatransp;
    @XmlElement(name = "CODI_MONED")
    protected short codimoned;
    @XmlElement(name = "FECH_INGSI")
    protected int fechingsi;
    @XmlElement(name = "HORA_INGSI", required = true)
    protected String horaingsi;
    @XmlElement(name = "ULTD_PAGO")
    protected int ultdpago;
    @XmlElement(name = "ID_MEDTRAN", required = true)
    protected String idmedtran;
    @XmlElement(name = "TRVJID")
    protected int trvjid;
    @XmlElement(name = "TIPO_TRAN", required = true)
    protected String tipotran;
    @XmlElement(name = "ASIG_EXTRA", required = true)
    protected String asigextra;
    @XmlElement(name = "CODI_REGI", required = true)
    protected String codiregi;
    @XmlElement(name = "ADUAINGEGR", required = true)
    protected String aduaingegr;
    @XmlElement(name = "NOMB_IMPOR", required = true)
    protected String nombimpor;
    @XmlElement(name = "DIRE_IMPOR", required = true)
    protected String direimpor;
    @XmlElement(name = "CODI_PAIS", required = true)
    protected String codipais;
    @XmlElement(name = "PAIS_TRANS", required = true)
    protected String paistrans;
    @XmlElement(name = "POLFECH_VENC")
    protected int polfechvenc;
    @XmlElement(name = "TOT_FACT")
    protected double totfact;
    @XmlElement(name = "POLDOBS", required = true)
    protected String poldobs;
    @XmlElement(name = "POLDEPDEST", required = true)
    protected String poldepdest;
    @XmlElement(name = "TIPO_AFORO", required = true)
    protected String tipoaforo;
    @XmlElement(name = "FECH_VISREAL")
    protected int fechvisreal;
    @XmlElement(name = "DCLATRASAL", required = true)
    protected String dclatrasal;
    @XmlElement(name = "NDNA_TRACT")
    protected long ndnatract;
    @XmlElement(name = "MATR_REMO", required = true)
    protected String matrremo;
    @XmlElement(name = "MATR_SREM", required = true)
    protected String matrsrem;
    @XmlElement(name = "TDOCEMPTRA", required = true)
    protected String tdocemptra;
    @XmlElement(name = "NDOCEMPTRA", required = true)
    protected String ndocemptra;
    @XmlElement(name = "CALMDEST", required = true)
    protected String calmdest;
    @XmlElement(name = "DCLATRALLE", required = true)
    protected String dclatralle;
    @XmlElement(name = "ADUNUMORI", required = true)
    protected String adunumori;
    @XmlElement(name = "TIPCAMVEN")
    protected double tipcamven;
    @XmlElement(name = "TIPCAMCOM")
    protected double tipcamcom;
    @XmlElement(name = "POLFECAUTS")
    protected int polfecauts;
    @XmlElement(name = "POLDUADIGI", required = true)
    protected String polduadigi;
    @XmlElement(name = "ITEMS", required = true)
    protected WSDUASDT.ITEMS items;
    @XmlElement(name = "ASOCIACIONES", required = true)
    protected WSDUASDT.ASOCIACIONES asociaciones;
    @XmlElement(name = "CONTENEDORES", required = true)
    protected WSDUASDT.CONTENEDORES contenedores;
    @XmlElement(name = "DOCUMENTOS", required = true)
    protected WSDUASDT.DOCUMENTOS documentos;
    @XmlElement(name = "FACTURAS", required = true)
    protected WSDUASDT.FACTURAS facturas;
    @XmlElement(name = "ENTRADASSTK", required = true)
    protected WSDUASDT.ENTRADASSTK entradasstk;
    @XmlElement(name = "MOVIMIENTOS", required = true)
    protected WSDUASDT.MOVIMIENTOS movimientos;
    @XmlElement(name = "CORRELACIONADOS", required = true)
    protected WSDUASDT.CORRELACIONADOS correlacionados;

    /**
     * Gets the value of the codiaduan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCODIADUAN() {
        return codiaduan;
    }

    /**
     * Sets the value of the codiaduan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCODIADUAN(String value) {
        this.codiaduan = value;
    }

    /**
     * Gets the value of the anoprese property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getANOPRESE() {
        return anoprese;
    }

    /**
     * Sets the value of the anoprese property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setANOPRESE(String value) {
        this.anoprese = value;
    }

    /**
     * Gets the value of the numecorre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNUMECORRE() {
        return numecorre;
    }

    /**
     * Sets the value of the numecorre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNUMECORRE(String value) {
        this.numecorre = value;
    }

    /**
     * Gets the value of the codialma property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCODIALMA() {
        return codialma;
    }

    /**
     * Sets the value of the codialma property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCODIALMA(String value) {
        this.codialma = value;
    }

    /**
     * Gets the value of the estado property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getESTADO() {
        return estado;
    }

    /**
     * Sets the value of the estado property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setESTADO(String value) {
        this.estado = value;
    }

    /**
     * Gets the value of the despurge property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDESPURGE() {
        return despurge;
    }

    /**
     * Sets the value of the despurge property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDESPURGE(String value) {
        this.despurge = value;
    }

    /**
     * Gets the value of the codiagent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCODIAGENT() {
        return codiagent;
    }

    /**
     * Sets the value of the codiagent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCODIAGENT(String value) {
        this.codiagent = value;
    }

    /**
     * Gets the value of the documentoAgente property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentoAgente() {
        return documentoAgente;
    }

    /**
     * Sets the value of the documentoAgente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentoAgente(String value) {
        this.documentoAgente = value;
    }

    /**
     * Gets the value of the tipoDocAgente property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoDocAgente() {
        return tipoDocAgente;
    }

    /**
     * Sets the value of the tipoDocAgente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoDocAgente(String value) {
        this.tipoDocAgente = value;
    }

    /**
     * Gets the value of the nombreAgente property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombreAgente() {
        return nombreAgente;
    }

    /**
     * Sets the value of the nombreAgente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombreAgente(String value) {
        this.nombreAgente = value;
    }

    /**
     * Gets the value of the numeorden property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNUMEORDEN() {
        return numeorden;
    }

    /**
     * Sets the value of the numeorden property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNUMEORDEN(String value) {
        this.numeorden = value;
    }

    /**
     * Gets the value of the ctipodoc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCTIPODOC() {
        return ctipodoc;
    }

    /**
     * Sets the value of the ctipodoc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCTIPODOC(String value) {
        this.ctipodoc = value;
    }

    /**
     * Gets the value of the cdocumen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCDOCUMEN() {
        return cdocumen;
    }

    /**
     * Sets the value of the cdocumen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCDOCUMEN(String value) {
        this.cdocumen = value;
    }

    /**
     * Gets the value of the unidtrans property.
     * 
     */
    public byte getUNIDTRANS() {
        return unidtrans;
    }

    /**
     * Sets the value of the unidtrans property.
     * 
     */
    public void setUNIDTRANS(byte value) {
        this.unidtrans = value;
    }

    /**
     * Gets the value of the viatransp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVIATRANSP() {
        return viatransp;
    }

    /**
     * Sets the value of the viatransp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVIATRANSP(String value) {
        this.viatransp = value;
    }

    /**
     * Gets the value of the codimoned property.
     * 
     */
    public short getCODIMONED() {
        return codimoned;
    }

    /**
     * Sets the value of the codimoned property.
     * 
     */
    public void setCODIMONED(short value) {
        this.codimoned = value;
    }

    /**
     * Gets the value of the fechingsi property.
     * 
     */
    public int getFECHINGSI() {
        return fechingsi;
    }

    /**
     * Sets the value of the fechingsi property.
     * 
     */
    public void setFECHINGSI(int value) {
        this.fechingsi = value;
    }

    /**
     * Gets the value of the horaingsi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHORAINGSI() {
        return horaingsi;
    }

    /**
     * Sets the value of the horaingsi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHORAINGSI(String value) {
        this.horaingsi = value;
    }

    /**
     * Gets the value of the ultdpago property.
     * 
     */
    public int getULTDPAGO() {
        return ultdpago;
    }

    /**
     * Sets the value of the ultdpago property.
     * 
     */
    public void setULTDPAGO(int value) {
        this.ultdpago = value;
    }

    /**
     * Gets the value of the idmedtran property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDMEDTRAN() {
        return idmedtran;
    }

    /**
     * Sets the value of the idmedtran property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDMEDTRAN(String value) {
        this.idmedtran = value;
    }

    /**
     * Gets the value of the trvjid property.
     * 
     */
    public int getTRVJID() {
        return trvjid;
    }

    /**
     * Sets the value of the trvjid property.
     * 
     */
    public void setTRVJID(int value) {
        this.trvjid = value;
    }

    /**
     * Gets the value of the tipotran property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTIPOTRAN() {
        return tipotran;
    }

    /**
     * Sets the value of the tipotran property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTIPOTRAN(String value) {
        this.tipotran = value;
    }

    /**
     * Gets the value of the asigextra property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getASIGEXTRA() {
        return asigextra;
    }

    /**
     * Sets the value of the asigextra property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setASIGEXTRA(String value) {
        this.asigextra = value;
    }

    /**
     * Gets the value of the codiregi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCODIREGI() {
        return codiregi;
    }

    /**
     * Sets the value of the codiregi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCODIREGI(String value) {
        this.codiregi = value;
    }

    /**
     * Gets the value of the aduaingegr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getADUAINGEGR() {
        return aduaingegr;
    }

    /**
     * Sets the value of the aduaingegr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setADUAINGEGR(String value) {
        this.aduaingegr = value;
    }

    /**
     * Gets the value of the nombimpor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNOMBIMPOR() {
        return nombimpor;
    }

    /**
     * Sets the value of the nombimpor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNOMBIMPOR(String value) {
        this.nombimpor = value;
    }

    /**
     * Gets the value of the direimpor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDIREIMPOR() {
        return direimpor;
    }

    /**
     * Sets the value of the direimpor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDIREIMPOR(String value) {
        this.direimpor = value;
    }

    /**
     * Gets the value of the codipais property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCODIPAIS() {
        return codipais;
    }

    /**
     * Sets the value of the codipais property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCODIPAIS(String value) {
        this.codipais = value;
    }

    /**
     * Gets the value of the paistrans property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPAISTRANS() {
        return paistrans;
    }

    /**
     * Sets the value of the paistrans property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPAISTRANS(String value) {
        this.paistrans = value;
    }

    /**
     * Gets the value of the polfechvenc property.
     * 
     */
    public int getPOLFECHVENC() {
        return polfechvenc;
    }

    /**
     * Sets the value of the polfechvenc property.
     * 
     */
    public void setPOLFECHVENC(int value) {
        this.polfechvenc = value;
    }

    /**
     * Gets the value of the totfact property.
     * 
     */
    public double getTOTFACT() {
        return totfact;
    }

    /**
     * Sets the value of the totfact property.
     * 
     */
    public void setTOTFACT(double value) {
        this.totfact = value;
    }

    /**
     * Gets the value of the poldobs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPOLDOBS() {
        return poldobs;
    }

    /**
     * Sets the value of the poldobs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPOLDOBS(String value) {
        this.poldobs = value;
    }

    /**
     * Gets the value of the poldepdest property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPOLDEPDEST() {
        return poldepdest;
    }

    /**
     * Sets the value of the poldepdest property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPOLDEPDEST(String value) {
        this.poldepdest = value;
    }

    /**
     * Gets the value of the tipoaforo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTIPOAFORO() {
        return tipoaforo;
    }

    /**
     * Sets the value of the tipoaforo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTIPOAFORO(String value) {
        this.tipoaforo = value;
    }

    /**
     * Gets the value of the fechvisreal property.
     * 
     */
    public int getFECHVISREAL() {
        return fechvisreal;
    }

    /**
     * Sets the value of the fechvisreal property.
     * 
     */
    public void setFECHVISREAL(int value) {
        this.fechvisreal = value;
    }

    /**
     * Gets the value of the dclatrasal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDCLATRASAL() {
        return dclatrasal;
    }

    /**
     * Sets the value of the dclatrasal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDCLATRASAL(String value) {
        this.dclatrasal = value;
    }

    /**
     * Gets the value of the ndnatract property.
     * 
     */
    public long getNDNATRACT() {
        return ndnatract;
    }

    /**
     * Sets the value of the ndnatract property.
     * 
     */
    public void setNDNATRACT(long value) {
        this.ndnatract = value;
    }

    /**
     * Gets the value of the matrremo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMATRREMO() {
        return matrremo;
    }

    /**
     * Sets the value of the matrremo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMATRREMO(String value) {
        this.matrremo = value;
    }

    /**
     * Gets the value of the matrsrem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMATRSREM() {
        return matrsrem;
    }

    /**
     * Sets the value of the matrsrem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMATRSREM(String value) {
        this.matrsrem = value;
    }

    /**
     * Gets the value of the tdocemptra property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTDOCEMPTRA() {
        return tdocemptra;
    }

    /**
     * Sets the value of the tdocemptra property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTDOCEMPTRA(String value) {
        this.tdocemptra = value;
    }

    /**
     * Gets the value of the ndocemptra property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNDOCEMPTRA() {
        return ndocemptra;
    }

    /**
     * Sets the value of the ndocemptra property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNDOCEMPTRA(String value) {
        this.ndocemptra = value;
    }

    /**
     * Gets the value of the calmdest property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCALMDEST() {
        return calmdest;
    }

    /**
     * Sets the value of the calmdest property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCALMDEST(String value) {
        this.calmdest = value;
    }

    /**
     * Gets the value of the dclatralle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDCLATRALLE() {
        return dclatralle;
    }

    /**
     * Sets the value of the dclatralle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDCLATRALLE(String value) {
        this.dclatralle = value;
    }

    /**
     * Gets the value of the adunumori property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getADUNUMORI() {
        return adunumori;
    }

    /**
     * Sets the value of the adunumori property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setADUNUMORI(String value) {
        this.adunumori = value;
    }

    /**
     * Gets the value of the tipcamven property.
     * 
     */
    public double getTIPCAMVEN() {
        return tipcamven;
    }

    /**
     * Sets the value of the tipcamven property.
     * 
     */
    public void setTIPCAMVEN(double value) {
        this.tipcamven = value;
    }

    /**
     * Gets the value of the tipcamcom property.
     * 
     */
    public double getTIPCAMCOM() {
        return tipcamcom;
    }

    /**
     * Sets the value of the tipcamcom property.
     * 
     */
    public void setTIPCAMCOM(double value) {
        this.tipcamcom = value;
    }

    /**
     * Gets the value of the polfecauts property.
     * 
     */
    public int getPOLFECAUTS() {
        return polfecauts;
    }

    /**
     * Sets the value of the polfecauts property.
     * 
     */
    public void setPOLFECAUTS(int value) {
        this.polfecauts = value;
    }

    /**
     * Gets the value of the polduadigi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPOLDUADIGI() {
        return polduadigi;
    }

    /**
     * Sets the value of the polduadigi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPOLDUADIGI(String value) {
        this.polduadigi = value;
    }

    /**
     * Gets the value of the items property.
     * 
     * @return
     *     possible object is
     *     {@link WSDUASDT.ITEMS }
     *     
     */
    public WSDUASDT.ITEMS getITEMS() {
        return items;
    }

    /**
     * Sets the value of the items property.
     * 
     * @param value
     *     allowed object is
     *     {@link WSDUASDT.ITEMS }
     *     
     */
    public void setITEMS(WSDUASDT.ITEMS value) {
        this.items = value;
    }

    /**
     * Gets the value of the asociaciones property.
     * 
     * @return
     *     possible object is
     *     {@link WSDUASDT.ASOCIACIONES }
     *     
     */
    public WSDUASDT.ASOCIACIONES getASOCIACIONES() {
        return asociaciones;
    }

    /**
     * Sets the value of the asociaciones property.
     * 
     * @param value
     *     allowed object is
     *     {@link WSDUASDT.ASOCIACIONES }
     *     
     */
    public void setASOCIACIONES(WSDUASDT.ASOCIACIONES value) {
        this.asociaciones = value;
    }

    /**
     * Gets the value of the contenedores property.
     * 
     * @return
     *     possible object is
     *     {@link WSDUASDT.CONTENEDORES }
     *     
     */
    public WSDUASDT.CONTENEDORES getCONTENEDORES() {
        return contenedores;
    }

    /**
     * Sets the value of the contenedores property.
     * 
     * @param value
     *     allowed object is
     *     {@link WSDUASDT.CONTENEDORES }
     *     
     */
    public void setCONTENEDORES(WSDUASDT.CONTENEDORES value) {
        this.contenedores = value;
    }

    /**
     * Gets the value of the documentos property.
     * 
     * @return
     *     possible object is
     *     {@link WSDUASDT.DOCUMENTOS }
     *     
     */
    public WSDUASDT.DOCUMENTOS getDOCUMENTOS() {
        return documentos;
    }

    /**
     * Sets the value of the documentos property.
     * 
     * @param value
     *     allowed object is
     *     {@link WSDUASDT.DOCUMENTOS }
     *     
     */
    public void setDOCUMENTOS(WSDUASDT.DOCUMENTOS value) {
        this.documentos = value;
    }

    /**
     * Gets the value of the facturas property.
     * 
     * @return
     *     possible object is
     *     {@link WSDUASDT.FACTURAS }
     *     
     */
    public WSDUASDT.FACTURAS getFACTURAS() {
        return facturas;
    }

    /**
     * Sets the value of the facturas property.
     * 
     * @param value
     *     allowed object is
     *     {@link WSDUASDT.FACTURAS }
     *     
     */
    public void setFACTURAS(WSDUASDT.FACTURAS value) {
        this.facturas = value;
    }

    /**
     * Gets the value of the entradasstk property.
     * 
     * @return
     *     possible object is
     *     {@link WSDUASDT.ENTRADASSTK }
     *     
     */
    public WSDUASDT.ENTRADASSTK getENTRADASSTK() {
        return entradasstk;
    }

    /**
     * Sets the value of the entradasstk property.
     * 
     * @param value
     *     allowed object is
     *     {@link WSDUASDT.ENTRADASSTK }
     *     
     */
    public void setENTRADASSTK(WSDUASDT.ENTRADASSTK value) {
        this.entradasstk = value;
    }

    /**
     * Gets the value of the movimientos property.
     * 
     * @return
     *     possible object is
     *     {@link WSDUASDT.MOVIMIENTOS }
     *     
     */
    public WSDUASDT.MOVIMIENTOS getMOVIMIENTOS() {
        return movimientos;
    }

    /**
     * Sets the value of the movimientos property.
     * 
     * @param value
     *     allowed object is
     *     {@link WSDUASDT.MOVIMIENTOS }
     *     
     */
    public void setMOVIMIENTOS(WSDUASDT.MOVIMIENTOS value) {
        this.movimientos = value;
    }

    /**
     * Gets the value of the correlacionados property.
     * 
     * @return
     *     possible object is
     *     {@link WSDUASDT.CORRELACIONADOS }
     *     
     */
    public WSDUASDT.CORRELACIONADOS getCORRELACIONADOS() {
        return correlacionados;
    }

    /**
     * Sets the value of the correlacionados property.
     * 
     * @param value
     *     allowed object is
     *     {@link WSDUASDT.CORRELACIONADOS }
     *     
     */
    public void setCORRELACIONADOS(WSDUASDT.CORRELACIONADOS value) {
        this.correlacionados = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ASOC" type="{www.aduanas.gub.uy/wsduasdt}WSDUASDT.ASOC" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "asoc"
    })
    public static class ASOCIACIONES {

        @XmlElement(name = "ASOC")
        protected List<WSDUASDTASOC> asoc;

        /**
         * Gets the value of the asoc property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the asoc property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getASOC().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link WSDUASDTASOC }
         * 
         * 
         */
        public List<WSDUASDTASOC> getASOC() {
            if (asoc == null) {
                asoc = new ArrayList<WSDUASDTASOC>();
            }
            return this.asoc;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CONTENEDOR" type="{www.aduanas.gub.uy/wsduasdt}WSDUASDT.CONTENEDOR" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "contenedor"
    })
    public static class CONTENEDORES {

        @XmlElement(name = "CONTENEDOR")
        protected List<WSDUASDTCONTENEDOR> contenedor;

        /**
         * Gets the value of the contenedor property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the contenedor property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCONTENEDOR().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link WSDUASDTCONTENEDOR }
         * 
         * 
         */
        public List<WSDUASDTCONTENEDOR> getCONTENEDOR() {
            if (contenedor == null) {
                contenedor = new ArrayList<WSDUASDTCONTENEDOR>();
            }
            return this.contenedor;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CORRELACIONADO" type="{www.aduanas.gub.uy/wsduasdt}WSDUASDT.CORRELACIONADO" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "correlacionado"
    })
    public static class CORRELACIONADOS {

        @XmlElement(name = "CORRELACIONADO")
        protected List<WSDUASDTCORRELACIONADO> correlacionado;

        /**
         * Gets the value of the correlacionado property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the correlacionado property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCORRELACIONADO().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link WSDUASDTCORRELACIONADO }
         * 
         * 
         */
        public List<WSDUASDTCORRELACIONADO> getCORRELACIONADO() {
            if (correlacionado == null) {
                correlacionado = new ArrayList<WSDUASDTCORRELACIONADO>();
            }
            return this.correlacionado;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DOCUMENTO" type="{www.aduanas.gub.uy/wsduasdt}WSDUASDT.DOCUMENTO" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "documento"
    })
    public static class DOCUMENTOS {

        @XmlElement(name = "DOCUMENTO")
        protected List<WSDUASDTDOCUMENTO> documento;

        /**
         * Gets the value of the documento property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the documento property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDOCUMENTO().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link WSDUASDTDOCUMENTO }
         * 
         * 
         */
        public List<WSDUASDTDOCUMENTO> getDOCUMENTO() {
            if (documento == null) {
                documento = new ArrayList<WSDUASDTDOCUMENTO>();
            }
            return this.documento;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ENTRADASTK" type="{www.aduanas.gub.uy/wsduasdt}WSDUASDT.ENTRADASTK" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "entradastk"
    })
    public static class ENTRADASSTK {

        @XmlElement(name = "ENTRADASTK")
        protected List<WSDUASDTENTRADASTK> entradastk;

        /**
         * Gets the value of the entradastk property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the entradastk property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getENTRADASTK().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link WSDUASDTENTRADASTK }
         * 
         * 
         */
        public List<WSDUASDTENTRADASTK> getENTRADASTK() {
            if (entradastk == null) {
                entradastk = new ArrayList<WSDUASDTENTRADASTK>();
            }
            return this.entradastk;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="FACTURA" type="{www.aduanas.gub.uy/wsduasdt}WSDUASDT.FACTURA" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "factura"
    })
    public static class FACTURAS {

        @XmlElement(name = "FACTURA")
        protected List<WSDUASDTFACTURA> factura;

        /**
         * Gets the value of the factura property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the factura property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFACTURA().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link WSDUASDTFACTURA }
         * 
         * 
         */
        public List<WSDUASDTFACTURA> getFACTURA() {
            if (factura == null) {
                factura = new ArrayList<WSDUASDTFACTURA>();
            }
            return this.factura;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ITEM" type="{www.aduanas.gub.uy/wsduasdt}WSDUASDT.ITEM" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "item"
    })
    public static class ITEMS {

        @XmlElement(name = "ITEM")
        protected List<WSDUASDTITEM> item;

        /**
         * Gets the value of the item property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the item property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getITEM().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link WSDUASDTITEM }
         * 
         * 
         */
        public List<WSDUASDTITEM> getITEM() {
            if (item == null) {
                item = new ArrayList<WSDUASDTITEM>();
            }
            return this.item;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="MOVIMIENTO" type="{www.aduanas.gub.uy/wsduasdt}WSDUASDT.MOVIMIENTO" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "movimiento"
    })
    public static class MOVIMIENTOS {

        @XmlElement(name = "MOVIMIENTO")
        protected List<WSDUASDTMOVIMIENTO> movimiento;

        /**
         * Gets the value of the movimiento property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the movimiento property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMOVIMIENTO().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link WSDUASDTMOVIMIENTO }
         * 
         * 
         */
        public List<WSDUASDTMOVIMIENTO> getMOVIMIENTO() {
            if (movimiento == null) {
                movimiento = new ArrayList<WSDUASDTMOVIMIENTO>();
            }
            return this.movimiento;
        }

    }

}
