//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.02 at 06:10:13 PM UYST 
//


package org.openup.aduana.dua.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for WSDUASDT.ENTRADASTK complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WSDUASDT.ENTRADASTK">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NUM" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="CGMItemDUA" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CGDepIdStk" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CGMovSkId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="CGAnoMov" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="CGMovTpo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CGMEstDUA" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CGMDUAOrg" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CGMDUAFch" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WSDUASDT.ENTRADASTK", propOrder = {
    "num",
    "cgmItemDUA",
    "cgDepIdStk",
    "cgMovSkId",
    "cgAnoMov",
    "cgMovTpo",
    "cgmEstDUA",
    "cgmduaOrg",
    "cgmduaFch"
})
public class WSDUASDTENTRADASTK {

    @XmlElement(name = "NUM")
    protected int num;
    @XmlElement(name = "CGMItemDUA", required = true)
    protected String cgmItemDUA;
    @XmlElement(name = "CGDepIdStk", required = true)
    protected String cgDepIdStk;
    @XmlElement(name = "CGMovSkId")
    protected long cgMovSkId;
    @XmlElement(name = "CGAnoMov")
    protected short cgAnoMov;
    @XmlElement(name = "CGMovTpo", required = true)
    protected String cgMovTpo;
    @XmlElement(name = "CGMEstDUA", required = true)
    protected String cgmEstDUA;
    @XmlElement(name = "CGMDUAOrg", required = true)
    protected String cgmduaOrg;
    @XmlElement(name = "CGMDUAFch", required = true, nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar cgmduaFch;

    /**
     * Gets the value of the num property.
     * 
     */
    public int getNUM() {
        return num;
    }

    /**
     * Sets the value of the num property.
     * 
     */
    public void setNUM(int value) {
        this.num = value;
    }

    /**
     * Gets the value of the cgmItemDUA property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCGMItemDUA() {
        return cgmItemDUA;
    }

    /**
     * Sets the value of the cgmItemDUA property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCGMItemDUA(String value) {
        this.cgmItemDUA = value;
    }

    /**
     * Gets the value of the cgDepIdStk property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCGDepIdStk() {
        return cgDepIdStk;
    }

    /**
     * Sets the value of the cgDepIdStk property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCGDepIdStk(String value) {
        this.cgDepIdStk = value;
    }

    /**
     * Gets the value of the cgMovSkId property.
     * 
     */
    public long getCGMovSkId() {
        return cgMovSkId;
    }

    /**
     * Sets the value of the cgMovSkId property.
     * 
     */
    public void setCGMovSkId(long value) {
        this.cgMovSkId = value;
    }

    /**
     * Gets the value of the cgAnoMov property.
     * 
     */
    public short getCGAnoMov() {
        return cgAnoMov;
    }

    /**
     * Sets the value of the cgAnoMov property.
     * 
     */
    public void setCGAnoMov(short value) {
        this.cgAnoMov = value;
    }

    /**
     * Gets the value of the cgMovTpo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCGMovTpo() {
        return cgMovTpo;
    }

    /**
     * Sets the value of the cgMovTpo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCGMovTpo(String value) {
        this.cgMovTpo = value;
    }

    /**
     * Gets the value of the cgmEstDUA property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCGMEstDUA() {
        return cgmEstDUA;
    }

    /**
     * Sets the value of the cgmEstDUA property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCGMEstDUA(String value) {
        this.cgmEstDUA = value;
    }

    /**
     * Gets the value of the cgmduaOrg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCGMDUAOrg() {
        return cgmduaOrg;
    }

    /**
     * Sets the value of the cgmduaOrg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCGMDUAOrg(String value) {
        this.cgmduaOrg = value;
    }

    /**
     * Gets the value of the cgmduaFch property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCGMDUAFch() {
        return cgmduaFch;
    }

    /**
     * Sets the value of the cgmduaFch property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCGMDUAFch(XMLGregorianCalendar value) {
        this.cgmduaFch = value;
    }

}
