//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.02 at 06:10:13 PM UYST 
//


package org.openup.aduana.dua.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WSDUASDT.DOCUMENTO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WSDUASDT.DOCUMENTO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NUM" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="NUME_SERIE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="COD_DOCCER" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FECH_VENC" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="NRO_DOCCER" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DIDCODUNI" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DIDTPOUNI" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DIDCNTUNI" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="MEIMAID" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WSDUASDT.DOCUMENTO", propOrder = {
    "num",
    "numeserie",
    "coddoccer",
    "fechvenc",
    "nrodoccer",
    "didcoduni",
    "didtpouni",
    "didcntuni",
    "meimaid"
})
public class WSDUASDTDOCUMENTO {

    @XmlElement(name = "NUM")
    protected int num;
    @XmlElement(name = "NUME_SERIE", required = true)
    protected String numeserie;
    @XmlElement(name = "COD_DOCCER", required = true)
    protected String coddoccer;
    @XmlElement(name = "FECH_VENC")
    protected int fechvenc;
    @XmlElement(name = "NRO_DOCCER", required = true)
    protected String nrodoccer;
    @XmlElement(name = "DIDCODUNI", required = true)
    protected String didcoduni;
    @XmlElement(name = "DIDTPOUNI", required = true)
    protected String didtpouni;
    @XmlElement(name = "DIDCNTUNI")
    protected double didcntuni;
    @XmlElement(name = "MEIMAID")
    protected long meimaid;

    /**
     * Gets the value of the num property.
     * 
     */
    public int getNUM() {
        return num;
    }

    /**
     * Sets the value of the num property.
     * 
     */
    public void setNUM(int value) {
        this.num = value;
    }

    /**
     * Gets the value of the numeserie property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNUMESERIE() {
        return numeserie;
    }

    /**
     * Sets the value of the numeserie property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNUMESERIE(String value) {
        this.numeserie = value;
    }

    /**
     * Gets the value of the coddoccer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCODDOCCER() {
        return coddoccer;
    }

    /**
     * Sets the value of the coddoccer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCODDOCCER(String value) {
        this.coddoccer = value;
    }

    /**
     * Gets the value of the fechvenc property.
     * 
     */
    public int getFECHVENC() {
        return fechvenc;
    }

    /**
     * Sets the value of the fechvenc property.
     * 
     */
    public void setFECHVENC(int value) {
        this.fechvenc = value;
    }

    /**
     * Gets the value of the nrodoccer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNRODOCCER() {
        return nrodoccer;
    }

    /**
     * Sets the value of the nrodoccer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNRODOCCER(String value) {
        this.nrodoccer = value;
    }

    /**
     * Gets the value of the didcoduni property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDIDCODUNI() {
        return didcoduni;
    }

    /**
     * Sets the value of the didcoduni property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDIDCODUNI(String value) {
        this.didcoduni = value;
    }

    /**
     * Gets the value of the didtpouni property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDIDTPOUNI() {
        return didtpouni;
    }

    /**
     * Sets the value of the didtpouni property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDIDTPOUNI(String value) {
        this.didtpouni = value;
    }

    /**
     * Gets the value of the didcntuni property.
     * 
     */
    public double getDIDCNTUNI() {
        return didcntuni;
    }

    /**
     * Sets the value of the didcntuni property.
     * 
     */
    public void setDIDCNTUNI(double value) {
        this.didcntuni = value;
    }

    /**
     * Gets the value of the meimaid property.
     * 
     */
    public long getMEIMAID() {
        return meimaid;
    }

    /**
     * Sets the value of the meimaid property.
     * 
     */
    public void setMEIMAID(long value) {
        this.meimaid = value;
    }

}
