//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.02 at 06:10:13 PM UYST 
//


package org.openup.aduana.dua.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for WSDUASDT.MOVIMIENTO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WSDUASDT.MOVIMIENTO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NUM" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="TRMOVORD" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="TRMOVRCT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TRMOVES" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TRMOVSTS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TRMOVPBRUTO" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="TRMOVPESO" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="TRMOVBULT" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="TRMOVMAT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TRMOVMATZ" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TRMOVMATR" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TRMOVFUNC" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TRMOVFCH" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="TRMOVHRA" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TRMOVANT" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="TRMOVMENS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TRMOVBZVac" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TRMOVBZLleno" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TRMOVCanal" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TRTryid" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Trconting" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WSDUASDT.MOVIMIENTO", propOrder = {
    "num",
    "trmovord",
    "trmovrct",
    "trmoves",
    "trmovsts",
    "trmovpbruto",
    "trmovpeso",
    "trmovbult",
    "trmovmat",
    "trmovmatz",
    "trmovmatr",
    "trmovfunc",
    "trmovfch",
    "trmovhra",
    "trmovant",
    "trmovmens",
    "trmovbzVac",
    "trmovbzLleno",
    "trmovCanal",
    "trTryid",
    "trconting"
})
public class WSDUASDTMOVIMIENTO {

    @XmlElement(name = "NUM")
    protected int num;
    @XmlElement(name = "TRMOVORD")
    protected int trmovord;
    @XmlElement(name = "TRMOVRCT", required = true)
    protected String trmovrct;
    @XmlElement(name = "TRMOVES", required = true)
    protected String trmoves;
    @XmlElement(name = "TRMOVSTS", required = true)
    protected String trmovsts;
    @XmlElement(name = "TRMOVPBRUTO")
    protected double trmovpbruto;
    @XmlElement(name = "TRMOVPESO")
    protected double trmovpeso;
    @XmlElement(name = "TRMOVBULT")
    protected double trmovbult;
    @XmlElement(name = "TRMOVMAT", required = true)
    protected String trmovmat;
    @XmlElement(name = "TRMOVMATZ", required = true)
    protected String trmovmatz;
    @XmlElement(name = "TRMOVMATR", required = true)
    protected String trmovmatr;
    @XmlElement(name = "TRMOVFUNC", required = true)
    protected String trmovfunc;
    @XmlElement(name = "TRMOVFCH", required = true, nillable = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar trmovfch;
    @XmlElement(name = "TRMOVHRA", required = true)
    protected String trmovhra;
    @XmlElement(name = "TRMOVANT")
    protected int trmovant;
    @XmlElement(name = "TRMOVMENS", required = true)
    protected String trmovmens;
    @XmlElement(name = "TRMOVBZVac", required = true)
    protected String trmovbzVac;
    @XmlElement(name = "TRMOVBZLleno", required = true)
    protected String trmovbzLleno;
    @XmlElement(name = "TRMOVCanal", required = true)
    protected String trmovCanal;
    @XmlElement(name = "TRTryid")
    protected int trTryid;
    @XmlElement(name = "Trconting", required = true)
    protected String trconting;

    /**
     * Gets the value of the num property.
     * 
     */
    public int getNUM() {
        return num;
    }

    /**
     * Sets the value of the num property.
     * 
     */
    public void setNUM(int value) {
        this.num = value;
    }

    /**
     * Gets the value of the trmovord property.
     * 
     */
    public int getTRMOVORD() {
        return trmovord;
    }

    /**
     * Sets the value of the trmovord property.
     * 
     */
    public void setTRMOVORD(int value) {
        this.trmovord = value;
    }

    /**
     * Gets the value of the trmovrct property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTRMOVRCT() {
        return trmovrct;
    }

    /**
     * Sets the value of the trmovrct property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTRMOVRCT(String value) {
        this.trmovrct = value;
    }

    /**
     * Gets the value of the trmoves property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTRMOVES() {
        return trmoves;
    }

    /**
     * Sets the value of the trmoves property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTRMOVES(String value) {
        this.trmoves = value;
    }

    /**
     * Gets the value of the trmovsts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTRMOVSTS() {
        return trmovsts;
    }

    /**
     * Sets the value of the trmovsts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTRMOVSTS(String value) {
        this.trmovsts = value;
    }

    /**
     * Gets the value of the trmovpbruto property.
     * 
     */
    public double getTRMOVPBRUTO() {
        return trmovpbruto;
    }

    /**
     * Sets the value of the trmovpbruto property.
     * 
     */
    public void setTRMOVPBRUTO(double value) {
        this.trmovpbruto = value;
    }

    /**
     * Gets the value of the trmovpeso property.
     * 
     */
    public double getTRMOVPESO() {
        return trmovpeso;
    }

    /**
     * Sets the value of the trmovpeso property.
     * 
     */
    public void setTRMOVPESO(double value) {
        this.trmovpeso = value;
    }

    /**
     * Gets the value of the trmovbult property.
     * 
     */
    public double getTRMOVBULT() {
        return trmovbult;
    }

    /**
     * Sets the value of the trmovbult property.
     * 
     */
    public void setTRMOVBULT(double value) {
        this.trmovbult = value;
    }

    /**
     * Gets the value of the trmovmat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTRMOVMAT() {
        return trmovmat;
    }

    /**
     * Sets the value of the trmovmat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTRMOVMAT(String value) {
        this.trmovmat = value;
    }

    /**
     * Gets the value of the trmovmatz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTRMOVMATZ() {
        return trmovmatz;
    }

    /**
     * Sets the value of the trmovmatz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTRMOVMATZ(String value) {
        this.trmovmatz = value;
    }

    /**
     * Gets the value of the trmovmatr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTRMOVMATR() {
        return trmovmatr;
    }

    /**
     * Sets the value of the trmovmatr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTRMOVMATR(String value) {
        this.trmovmatr = value;
    }

    /**
     * Gets the value of the trmovfunc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTRMOVFUNC() {
        return trmovfunc;
    }

    /**
     * Sets the value of the trmovfunc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTRMOVFUNC(String value) {
        this.trmovfunc = value;
    }

    /**
     * Gets the value of the trmovfch property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTRMOVFCH() {
        return trmovfch;
    }

    /**
     * Sets the value of the trmovfch property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTRMOVFCH(XMLGregorianCalendar value) {
        this.trmovfch = value;
    }

    /**
     * Gets the value of the trmovhra property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTRMOVHRA() {
        return trmovhra;
    }

    /**
     * Sets the value of the trmovhra property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTRMOVHRA(String value) {
        this.trmovhra = value;
    }

    /**
     * Gets the value of the trmovant property.
     * 
     */
    public int getTRMOVANT() {
        return trmovant;
    }

    /**
     * Sets the value of the trmovant property.
     * 
     */
    public void setTRMOVANT(int value) {
        this.trmovant = value;
    }

    /**
     * Gets the value of the trmovmens property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTRMOVMENS() {
        return trmovmens;
    }

    /**
     * Sets the value of the trmovmens property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTRMOVMENS(String value) {
        this.trmovmens = value;
    }

    /**
     * Gets the value of the trmovbzVac property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTRMOVBZVac() {
        return trmovbzVac;
    }

    /**
     * Sets the value of the trmovbzVac property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTRMOVBZVac(String value) {
        this.trmovbzVac = value;
    }

    /**
     * Gets the value of the trmovbzLleno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTRMOVBZLleno() {
        return trmovbzLleno;
    }

    /**
     * Sets the value of the trmovbzLleno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTRMOVBZLleno(String value) {
        this.trmovbzLleno = value;
    }

    /**
     * Gets the value of the trmovCanal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTRMOVCanal() {
        return trmovCanal;
    }

    /**
     * Sets the value of the trmovCanal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTRMOVCanal(String value) {
        this.trmovCanal = value;
    }

    /**
     * Gets the value of the trTryid property.
     * 
     */
    public int getTRTryid() {
        return trTryid;
    }

    /**
     * Sets the value of the trTryid property.
     * 
     */
    public void setTRTryid(int value) {
        this.trTryid = value;
    }

    /**
     * Gets the value of the trconting property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrconting() {
        return trconting;
    }

    /**
     * Sets the value of the trconting property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrconting(String value) {
        this.trconting = value;
    }

}
