//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.02 at 06:10:13 PM UYST 
//


package org.openup.aduana.dua.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Codi_aduan" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Ano_prese" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Nume_corre" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "codiAduan",
    "anoPrese",
    "numeCorre"
})
@XmlRootElement(name = "WSDUA.Execute", namespace = "www.aduanas.gub.uy/wsdua")
public class WSDUAExecute {

    @XmlElement(name = "Codi_aduan", namespace = "www.aduanas.gub.uy/wsdua", required = true)
    protected String codiAduan;
    @XmlElement(name = "Ano_prese", namespace = "www.aduanas.gub.uy/wsdua", required = true)
    protected String anoPrese;
    @XmlElement(name = "Nume_corre", namespace = "www.aduanas.gub.uy/wsdua", required = true)
    protected String numeCorre;

    /**
     * Gets the value of the codiAduan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodiAduan() {
        return codiAduan;
    }

    /**
     * Sets the value of the codiAduan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodiAduan(String value) {
        this.codiAduan = value;
    }

    /**
     * Gets the value of the anoPrese property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnoPrese() {
        return anoPrese;
    }

    /**
     * Sets the value of the anoPrese property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnoPrese(String value) {
        this.anoPrese = value;
    }

    /**
     * Gets the value of the numeCorre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeCorre() {
        return numeCorre;
    }

    /**
     * Sets the value of the numeCorre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeCorre(String value) {
        this.numeCorre = value;
    }

}
