//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.02 at 06:10:13 PM UYST 
//


package org.openup.aduana.dua.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WSDUASDT.ITEM complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WSDUASDT.ITEM">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NUM" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="NUME_SERIE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="COD_DOCCA" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MARCAS_NUM" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CLASE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CANT_BULTO" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="DESC01" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DESC02" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DESC03" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DESC04" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DESC05" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PESO_NETO" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="PESO_BRUTO" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="PARTIDA" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="CPROD" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PAIS_ORIGE" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="UNID_FIQTY" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="UNID_FIDES" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CODI_LIBER" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="CONV_INTER" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="QUNICOM" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="TUNICOM" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PUER_EMBAR" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="PAIS_ADQUI" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="CIF_DOLPOL" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="VAD_INCR" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="TIPO_OPERA" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CNT_ANALI" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="TDOCDEST" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NDOCDEST" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NOMDOCDEST" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WSDUASDT.ITEM", propOrder = {
    "num",
    "numeserie",
    "coddocca",
    "marcasnum",
    "clase",
    "cantbulto",
    "desc01",
    "desc02",
    "desc03",
    "desc04",
    "desc05",
    "pesoneto",
    "pesobruto",
    "partida",
    "cprod",
    "paisorige",
    "unidfiqty",
    "unidfides",
    "codiliber",
    "convinter",
    "qunicom",
    "tunicom",
    "puerembar",
    "paisadqui",
    "cifdolpol",
    "vadincr",
    "tipoopera",
    "cntanali",
    "tdocdest",
    "ndocdest",
    "nomdocdest"
})
public class WSDUASDTITEM {

    @XmlElement(name = "NUM")
    protected int num;
    @XmlElement(name = "NUME_SERIE", required = true)
    protected String numeserie;
    @XmlElement(name = "COD_DOCCA", required = true)
    protected String coddocca;
    @XmlElement(name = "MARCAS_NUM", required = true)
    protected String marcasnum;
    @XmlElement(name = "CLASE", required = true)
    protected String clase;
    @XmlElement(name = "CANT_BULTO")
    protected double cantbulto;
    @XmlElement(name = "DESC01", required = true)
    protected String desc01;
    @XmlElement(name = "DESC02", required = true)
    protected String desc02;
    @XmlElement(name = "DESC03", required = true)
    protected String desc03;
    @XmlElement(name = "DESC04", required = true)
    protected String desc04;
    @XmlElement(name = "DESC05", required = true)
    protected String desc05;
    @XmlElement(name = "PESO_NETO")
    protected double pesoneto;
    @XmlElement(name = "PESO_BRUTO")
    protected double pesobruto;
    @XmlElement(name = "PARTIDA")
    protected long partida;
    @XmlElement(name = "CPROD", required = true)
    protected String cprod;
    @XmlElement(name = "PAIS_ORIGE")
    protected short paisorige;
    @XmlElement(name = "UNID_FIQTY")
    protected double unidfiqty;
    @XmlElement(name = "UNID_FIDES", required = true)
    protected String unidfides;
    @XmlElement(name = "CODI_LIBER")
    protected short codiliber;
    @XmlElement(name = "CONV_INTER")
    protected short convinter;
    @XmlElement(name = "QUNICOM")
    protected double qunicom;
    @XmlElement(name = "TUNICOM", required = true)
    protected String tunicom;
    @XmlElement(name = "PUER_EMBAR")
    protected short puerembar;
    @XmlElement(name = "PAIS_ADQUI")
    protected short paisadqui;
    @XmlElement(name = "CIF_DOLPOL")
    protected double cifdolpol;
    @XmlElement(name = "VAD_INCR")
    protected double vadincr;
    @XmlElement(name = "TIPO_OPERA", required = true)
    protected String tipoopera;
    @XmlElement(name = "CNT_ANALI")
    protected byte cntanali;
    @XmlElement(name = "TDOCDEST", required = true)
    protected String tdocdest;
    @XmlElement(name = "NDOCDEST", required = true)
    protected String ndocdest;
    @XmlElement(name = "NOMDOCDEST", required = true)
    protected String nomdocdest;

    /**
     * Gets the value of the num property.
     * 
     */
    public int getNUM() {
        return num;
    }

    /**
     * Sets the value of the num property.
     * 
     */
    public void setNUM(int value) {
        this.num = value;
    }

    /**
     * Gets the value of the numeserie property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNUMESERIE() {
        return numeserie;
    }

    /**
     * Sets the value of the numeserie property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNUMESERIE(String value) {
        this.numeserie = value;
    }

    /**
     * Gets the value of the coddocca property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCODDOCCA() {
        return coddocca;
    }

    /**
     * Sets the value of the coddocca property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCODDOCCA(String value) {
        this.coddocca = value;
    }

    /**
     * Gets the value of the marcasnum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMARCASNUM() {
        return marcasnum;
    }

    /**
     * Sets the value of the marcasnum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMARCASNUM(String value) {
        this.marcasnum = value;
    }

    /**
     * Gets the value of the clase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCLASE() {
        return clase;
    }

    /**
     * Sets the value of the clase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCLASE(String value) {
        this.clase = value;
    }

    /**
     * Gets the value of the cantbulto property.
     * 
     */
    public double getCANTBULTO() {
        return cantbulto;
    }

    /**
     * Sets the value of the cantbulto property.
     * 
     */
    public void setCANTBULTO(double value) {
        this.cantbulto = value;
    }

    /**
     * Gets the value of the desc01 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDESC01() {
        return desc01;
    }

    /**
     * Sets the value of the desc01 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDESC01(String value) {
        this.desc01 = value;
    }

    /**
     * Gets the value of the desc02 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDESC02() {
        return desc02;
    }

    /**
     * Sets the value of the desc02 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDESC02(String value) {
        this.desc02 = value;
    }

    /**
     * Gets the value of the desc03 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDESC03() {
        return desc03;
    }

    /**
     * Sets the value of the desc03 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDESC03(String value) {
        this.desc03 = value;
    }

    /**
     * Gets the value of the desc04 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDESC04() {
        return desc04;
    }

    /**
     * Sets the value of the desc04 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDESC04(String value) {
        this.desc04 = value;
    }

    /**
     * Gets the value of the desc05 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDESC05() {
        return desc05;
    }

    /**
     * Sets the value of the desc05 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDESC05(String value) {
        this.desc05 = value;
    }

    /**
     * Gets the value of the pesoneto property.
     * 
     */
    public double getPESONETO() {
        return pesoneto;
    }

    /**
     * Sets the value of the pesoneto property.
     * 
     */
    public void setPESONETO(double value) {
        this.pesoneto = value;
    }

    /**
     * Gets the value of the pesobruto property.
     * 
     */
    public double getPESOBRUTO() {
        return pesobruto;
    }

    /**
     * Sets the value of the pesobruto property.
     * 
     */
    public void setPESOBRUTO(double value) {
        this.pesobruto = value;
    }

    /**
     * Gets the value of the partida property.
     * 
     */
    public long getPARTIDA() {
        return partida;
    }

    /**
     * Sets the value of the partida property.
     * 
     */
    public void setPARTIDA(long value) {
        this.partida = value;
    }

    /**
     * Gets the value of the cprod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPROD() {
        return cprod;
    }

    /**
     * Sets the value of the cprod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPROD(String value) {
        this.cprod = value;
    }

    /**
     * Gets the value of the paisorige property.
     * 
     */
    public short getPAISORIGE() {
        return paisorige;
    }

    /**
     * Sets the value of the paisorige property.
     * 
     */
    public void setPAISORIGE(short value) {
        this.paisorige = value;
    }

    /**
     * Gets the value of the unidfiqty property.
     * 
     */
    public double getUNIDFIQTY() {
        return unidfiqty;
    }

    /**
     * Sets the value of the unidfiqty property.
     * 
     */
    public void setUNIDFIQTY(double value) {
        this.unidfiqty = value;
    }

    /**
     * Gets the value of the unidfides property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUNIDFIDES() {
        return unidfides;
    }

    /**
     * Sets the value of the unidfides property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUNIDFIDES(String value) {
        this.unidfides = value;
    }

    /**
     * Gets the value of the codiliber property.
     * 
     */
    public short getCODILIBER() {
        return codiliber;
    }

    /**
     * Sets the value of the codiliber property.
     * 
     */
    public void setCODILIBER(short value) {
        this.codiliber = value;
    }

    /**
     * Gets the value of the convinter property.
     * 
     */
    public short getCONVINTER() {
        return convinter;
    }

    /**
     * Sets the value of the convinter property.
     * 
     */
    public void setCONVINTER(short value) {
        this.convinter = value;
    }

    /**
     * Gets the value of the qunicom property.
     * 
     */
    public double getQUNICOM() {
        return qunicom;
    }

    /**
     * Sets the value of the qunicom property.
     * 
     */
    public void setQUNICOM(double value) {
        this.qunicom = value;
    }

    /**
     * Gets the value of the tunicom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTUNICOM() {
        return tunicom;
    }

    /**
     * Sets the value of the tunicom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTUNICOM(String value) {
        this.tunicom = value;
    }

    /**
     * Gets the value of the puerembar property.
     * 
     */
    public short getPUEREMBAR() {
        return puerembar;
    }

    /**
     * Sets the value of the puerembar property.
     * 
     */
    public void setPUEREMBAR(short value) {
        this.puerembar = value;
    }

    /**
     * Gets the value of the paisadqui property.
     * 
     */
    public short getPAISADQUI() {
        return paisadqui;
    }

    /**
     * Sets the value of the paisadqui property.
     * 
     */
    public void setPAISADQUI(short value) {
        this.paisadqui = value;
    }

    /**
     * Gets the value of the cifdolpol property.
     * 
     */
    public double getCIFDOLPOL() {
        return cifdolpol;
    }

    /**
     * Sets the value of the cifdolpol property.
     * 
     */
    public void setCIFDOLPOL(double value) {
        this.cifdolpol = value;
    }

    /**
     * Gets the value of the vadincr property.
     * 
     */
    public double getVADINCR() {
        return vadincr;
    }

    /**
     * Sets the value of the vadincr property.
     * 
     */
    public void setVADINCR(double value) {
        this.vadincr = value;
    }

    /**
     * Gets the value of the tipoopera property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTIPOOPERA() {
        return tipoopera;
    }

    /**
     * Sets the value of the tipoopera property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTIPOOPERA(String value) {
        this.tipoopera = value;
    }

    /**
     * Gets the value of the cntanali property.
     * 
     */
    public byte getCNTANALI() {
        return cntanali;
    }

    /**
     * Sets the value of the cntanali property.
     * 
     */
    public void setCNTANALI(byte value) {
        this.cntanali = value;
    }

    /**
     * Gets the value of the tdocdest property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTDOCDEST() {
        return tdocdest;
    }

    /**
     * Sets the value of the tdocdest property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTDOCDEST(String value) {
        this.tdocdest = value;
    }

    /**
     * Gets the value of the ndocdest property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNDOCDEST() {
        return ndocdest;
    }

    /**
     * Sets the value of the ndocdest property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNDOCDEST(String value) {
        this.ndocdest = value;
    }

    /**
     * Gets the value of the nomdocdest property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNOMDOCDEST() {
        return nomdocdest;
    }

    /**
     * Sets the value of the nomdocdest property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNOMDOCDEST(String value) {
        this.nomdocdest = value;
    }

}
