//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.02 at 06:10:13 PM UYST 
//


package org.openup.aduana.dua.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WSDUASDT.FACTURA complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WSDUASDT.FACTURA">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NUM" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="NUME_SERIE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NUME_FACTU" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FECH_FACTU" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="TERM_TRANS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LUGARTRANS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="COD_DOCCER" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ITEM_FACTU" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="MSDOCGRLID" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="MSDOCIMPAS" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="MSDOCCNTAS" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="MEIMAID" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="MSDOMDA" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WSDUASDT.FACTURA", propOrder = {
    "num",
    "numeserie",
    "numefactu",
    "fechfactu",
    "termtrans",
    "lugartrans",
    "coddoccer",
    "itemfactu",
    "msdocgrlid",
    "msdocimpas",
    "msdoccntas",
    "meimaid",
    "msdomda"
})
public class WSDUASDTFACTURA {

    @XmlElement(name = "NUM")
    protected int num;
    @XmlElement(name = "NUME_SERIE", required = true)
    protected String numeserie;
    @XmlElement(name = "NUME_FACTU", required = true)
    protected String numefactu;
    @XmlElement(name = "FECH_FACTU")
    protected int fechfactu;
    @XmlElement(name = "TERM_TRANS", required = true)
    protected String termtrans;
    @XmlElement(name = "LUGARTRANS", required = true)
    protected String lugartrans;
    @XmlElement(name = "COD_DOCCER", required = true)
    protected String coddoccer;
    @XmlElement(name = "ITEM_FACTU")
    protected short itemfactu;
    @XmlElement(name = "MSDOCGRLID")
    protected long msdocgrlid;
    @XmlElement(name = "MSDOCIMPAS")
    protected double msdocimpas;
    @XmlElement(name = "MSDOCCNTAS")
    protected double msdoccntas;
    @XmlElement(name = "MEIMAID")
    protected long meimaid;
    @XmlElement(name = "MSDOMDA", required = true)
    protected String msdomda;

    /**
     * Gets the value of the num property.
     * 
     */
    public int getNUM() {
        return num;
    }

    /**
     * Sets the value of the num property.
     * 
     */
    public void setNUM(int value) {
        this.num = value;
    }

    /**
     * Gets the value of the numeserie property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNUMESERIE() {
        return numeserie;
    }

    /**
     * Sets the value of the numeserie property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNUMESERIE(String value) {
        this.numeserie = value;
    }

    /**
     * Gets the value of the numefactu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNUMEFACTU() {
        return numefactu;
    }

    /**
     * Sets the value of the numefactu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNUMEFACTU(String value) {
        this.numefactu = value;
    }

    /**
     * Gets the value of the fechfactu property.
     * 
     */
    public int getFECHFACTU() {
        return fechfactu;
    }

    /**
     * Sets the value of the fechfactu property.
     * 
     */
    public void setFECHFACTU(int value) {
        this.fechfactu = value;
    }

    /**
     * Gets the value of the termtrans property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTERMTRANS() {
        return termtrans;
    }

    /**
     * Sets the value of the termtrans property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTERMTRANS(String value) {
        this.termtrans = value;
    }

    /**
     * Gets the value of the lugartrans property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLUGARTRANS() {
        return lugartrans;
    }

    /**
     * Sets the value of the lugartrans property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLUGARTRANS(String value) {
        this.lugartrans = value;
    }

    /**
     * Gets the value of the coddoccer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCODDOCCER() {
        return coddoccer;
    }

    /**
     * Sets the value of the coddoccer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCODDOCCER(String value) {
        this.coddoccer = value;
    }

    /**
     * Gets the value of the itemfactu property.
     * 
     */
    public short getITEMFACTU() {
        return itemfactu;
    }

    /**
     * Sets the value of the itemfactu property.
     * 
     */
    public void setITEMFACTU(short value) {
        this.itemfactu = value;
    }

    /**
     * Gets the value of the msdocgrlid property.
     * 
     */
    public long getMSDOCGRLID() {
        return msdocgrlid;
    }

    /**
     * Sets the value of the msdocgrlid property.
     * 
     */
    public void setMSDOCGRLID(long value) {
        this.msdocgrlid = value;
    }

    /**
     * Gets the value of the msdocimpas property.
     * 
     */
    public double getMSDOCIMPAS() {
        return msdocimpas;
    }

    /**
     * Sets the value of the msdocimpas property.
     * 
     */
    public void setMSDOCIMPAS(double value) {
        this.msdocimpas = value;
    }

    /**
     * Gets the value of the msdoccntas property.
     * 
     */
    public double getMSDOCCNTAS() {
        return msdoccntas;
    }

    /**
     * Sets the value of the msdoccntas property.
     * 
     */
    public void setMSDOCCNTAS(double value) {
        this.msdoccntas = value;
    }

    /**
     * Gets the value of the meimaid property.
     * 
     */
    public long getMEIMAID() {
        return meimaid;
    }

    /**
     * Sets the value of the meimaid property.
     * 
     */
    public void setMEIMAID(long value) {
        this.meimaid = value;
    }

    /**
     * Gets the value of the msdomda property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMSDOMDA() {
        return msdomda;
    }

    /**
     * Sets the value of the msdomda property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMSDOMDA(String value) {
        this.msdomda = value;
    }

}
