//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.02 at 06:10:13 PM UYST 
//


package org.openup.aduana.dua.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WSDUASDT.CONTENEDOR complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WSDUASDT.CONTENEDOR">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NUM" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="NUME_SECUE" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="CNT_NUMERO" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CNT_PRECIN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CNT_MEDID" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="CNT_PRECI2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CNT_PRECI3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CNT_DEPDES" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CNT_MANDES" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CNT_FMANDE" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WSDUASDT.CONTENEDOR", propOrder = {
    "num",
    "numesecue",
    "cntnumero",
    "cntprecin",
    "cntmedid",
    "cntpreci2",
    "cntpreci3",
    "cntdepdes",
    "cntmandes",
    "cntfmande"
})
public class WSDUASDTCONTENEDOR {

    @XmlElement(name = "NUM")
    protected int num;
    @XmlElement(name = "NUME_SECUE")
    protected short numesecue;
    @XmlElement(name = "CNT_NUMERO", required = true)
    protected String cntnumero;
    @XmlElement(name = "CNT_PRECIN", required = true)
    protected String cntprecin;
    @XmlElement(name = "CNT_MEDID")
    protected short cntmedid;
    @XmlElement(name = "CNT_PRECI2", required = true)
    protected String cntpreci2;
    @XmlElement(name = "CNT_PRECI3", required = true)
    protected String cntpreci3;
    @XmlElement(name = "CNT_DEPDES", required = true)
    protected String cntdepdes;
    @XmlElement(name = "CNT_MANDES", required = true)
    protected String cntmandes;
    @XmlElement(name = "CNT_FMANDE")
    protected int cntfmande;

    /**
     * Gets the value of the num property.
     * 
     */
    public int getNUM() {
        return num;
    }

    /**
     * Sets the value of the num property.
     * 
     */
    public void setNUM(int value) {
        this.num = value;
    }

    /**
     * Gets the value of the numesecue property.
     * 
     */
    public short getNUMESECUE() {
        return numesecue;
    }

    /**
     * Sets the value of the numesecue property.
     * 
     */
    public void setNUMESECUE(short value) {
        this.numesecue = value;
    }

    /**
     * Gets the value of the cntnumero property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCNTNUMERO() {
        return cntnumero;
    }

    /**
     * Sets the value of the cntnumero property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCNTNUMERO(String value) {
        this.cntnumero = value;
    }

    /**
     * Gets the value of the cntprecin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCNTPRECIN() {
        return cntprecin;
    }

    /**
     * Sets the value of the cntprecin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCNTPRECIN(String value) {
        this.cntprecin = value;
    }

    /**
     * Gets the value of the cntmedid property.
     * 
     */
    public short getCNTMEDID() {
        return cntmedid;
    }

    /**
     * Sets the value of the cntmedid property.
     * 
     */
    public void setCNTMEDID(short value) {
        this.cntmedid = value;
    }

    /**
     * Gets the value of the cntpreci2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCNTPRECI2() {
        return cntpreci2;
    }

    /**
     * Sets the value of the cntpreci2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCNTPRECI2(String value) {
        this.cntpreci2 = value;
    }

    /**
     * Gets the value of the cntpreci3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCNTPRECI3() {
        return cntpreci3;
    }

    /**
     * Sets the value of the cntpreci3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCNTPRECI3(String value) {
        this.cntpreci3 = value;
    }

    /**
     * Gets the value of the cntdepdes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCNTDEPDES() {
        return cntdepdes;
    }

    /**
     * Sets the value of the cntdepdes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCNTDEPDES(String value) {
        this.cntdepdes = value;
    }

    /**
     * Gets the value of the cntmandes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCNTMANDES() {
        return cntmandes;
    }

    /**
     * Sets the value of the cntmandes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCNTMANDES(String value) {
        this.cntmandes = value;
    }

    /**
     * Gets the value of the cntfmande property.
     * 
     */
    public int getCNTFMANDE() {
        return cntfmande;
    }

    /**
     * Sets the value of the cntfmande property.
     * 
     */
    public void setCNTFMANDE(int value) {
        this.cntfmande = value;
    }

}
