//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.02 at 06:10:13 PM UYST 
//


package org.openup.aduana.dua.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WSDUASDT.ASOC complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WSDUASDT.ASOC">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NUM" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="NUME_SERIE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CGTpoTrans" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CGTpoMic" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CGNroMic" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RGDepID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CGFchArr" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="CGNroConDNA" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="CGNroLin" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="CGNroMovAso" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="CGAnoMovAso" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="CGDepoAso" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CGCntBulAso" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="CGEstAsoD" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WSDUASDT.ASOC", propOrder = {
    "num",
    "numeserie",
    "cgTpoTrans",
    "cgTpoMic",
    "cgNroMic",
    "rgDepID",
    "cgFchArr",
    "cgNroConDNA",
    "cgNroLin",
    "cgNroMovAso",
    "cgAnoMovAso",
    "cgDepoAso",
    "cgCntBulAso",
    "cgEstAsoD"
})
public class WSDUASDTASOC {

    @XmlElement(name = "NUM")
    protected int num;
    @XmlElement(name = "NUME_SERIE", required = true)
    protected String numeserie;
    @XmlElement(name = "CGTpoTrans", required = true)
    protected String cgTpoTrans;
    @XmlElement(name = "CGTpoMic", required = true)
    protected String cgTpoMic;
    @XmlElement(name = "CGNroMic", required = true)
    protected String cgNroMic;
    @XmlElement(name = "RGDepID", required = true)
    protected String rgDepID;
    @XmlElement(name = "CGFchArr")
    protected int cgFchArr;
    @XmlElement(name = "CGNroConDNA")
    protected short cgNroConDNA;
    @XmlElement(name = "CGNroLin")
    protected short cgNroLin;
    @XmlElement(name = "CGNroMovAso")
    protected long cgNroMovAso;
    @XmlElement(name = "CGAnoMovAso")
    protected short cgAnoMovAso;
    @XmlElement(name = "CGDepoAso", required = true)
    protected String cgDepoAso;
    @XmlElement(name = "CGCntBulAso")
    protected double cgCntBulAso;
    @XmlElement(name = "CGEstAsoD", required = true)
    protected String cgEstAsoD;

    /**
     * Gets the value of the num property.
     * 
     */
    public int getNUM() {
        return num;
    }

    /**
     * Sets the value of the num property.
     * 
     */
    public void setNUM(int value) {
        this.num = value;
    }

    /**
     * Gets the value of the numeserie property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNUMESERIE() {
        return numeserie;
    }

    /**
     * Sets the value of the numeserie property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNUMESERIE(String value) {
        this.numeserie = value;
    }

    /**
     * Gets the value of the cgTpoTrans property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCGTpoTrans() {
        return cgTpoTrans;
    }

    /**
     * Sets the value of the cgTpoTrans property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCGTpoTrans(String value) {
        this.cgTpoTrans = value;
    }

    /**
     * Gets the value of the cgTpoMic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCGTpoMic() {
        return cgTpoMic;
    }

    /**
     * Sets the value of the cgTpoMic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCGTpoMic(String value) {
        this.cgTpoMic = value;
    }

    /**
     * Gets the value of the cgNroMic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCGNroMic() {
        return cgNroMic;
    }

    /**
     * Sets the value of the cgNroMic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCGNroMic(String value) {
        this.cgNroMic = value;
    }

    /**
     * Gets the value of the rgDepID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRGDepID() {
        return rgDepID;
    }

    /**
     * Sets the value of the rgDepID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRGDepID(String value) {
        this.rgDepID = value;
    }

    /**
     * Gets the value of the cgFchArr property.
     * 
     */
    public int getCGFchArr() {
        return cgFchArr;
    }

    /**
     * Sets the value of the cgFchArr property.
     * 
     */
    public void setCGFchArr(int value) {
        this.cgFchArr = value;
    }

    /**
     * Gets the value of the cgNroConDNA property.
     * 
     */
    public short getCGNroConDNA() {
        return cgNroConDNA;
    }

    /**
     * Sets the value of the cgNroConDNA property.
     * 
     */
    public void setCGNroConDNA(short value) {
        this.cgNroConDNA = value;
    }

    /**
     * Gets the value of the cgNroLin property.
     * 
     */
    public short getCGNroLin() {
        return cgNroLin;
    }

    /**
     * Sets the value of the cgNroLin property.
     * 
     */
    public void setCGNroLin(short value) {
        this.cgNroLin = value;
    }

    /**
     * Gets the value of the cgNroMovAso property.
     * 
     */
    public long getCGNroMovAso() {
        return cgNroMovAso;
    }

    /**
     * Sets the value of the cgNroMovAso property.
     * 
     */
    public void setCGNroMovAso(long value) {
        this.cgNroMovAso = value;
    }

    /**
     * Gets the value of the cgAnoMovAso property.
     * 
     */
    public short getCGAnoMovAso() {
        return cgAnoMovAso;
    }

    /**
     * Sets the value of the cgAnoMovAso property.
     * 
     */
    public void setCGAnoMovAso(short value) {
        this.cgAnoMovAso = value;
    }

    /**
     * Gets the value of the cgDepoAso property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCGDepoAso() {
        return cgDepoAso;
    }

    /**
     * Sets the value of the cgDepoAso property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCGDepoAso(String value) {
        this.cgDepoAso = value;
    }

    /**
     * Gets the value of the cgCntBulAso property.
     * 
     */
    public double getCGCntBulAso() {
        return cgCntBulAso;
    }

    /**
     * Sets the value of the cgCntBulAso property.
     * 
     */
    public void setCGCntBulAso(double value) {
        this.cgCntBulAso = value;
    }

    /**
     * Gets the value of the cgEstAsoD property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCGEstAsoD() {
        return cgEstAsoD;
    }

    /**
     * Sets the value of the cgEstAsoD property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCGEstAsoD(String value) {
        this.cgEstAsoD = value;
    }

}
