
package org.openup.aduana.crt.conexion.produccion;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "wsImagenSoapPort", targetNamespace = "www.aduanas.gub.uy/DAE")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsImagenSoapPort {


    /**
     * 
     * @param parameters
     * @return
     *     returns uy.gub.aduanas.dae.WsImagenExecuteResponse
     */
    @WebMethod(operationName = "Execute", action = "www.aduanas.gub.uy/DAEaction/AWSIMAGEN.Execute")
    @WebResult(name = "wsImagen.ExecuteResponse", targetNamespace = "www.aduanas.gub.uy/DAE", partName = "parameters")
    public WsImagenExecuteResponse execute(
        @WebParam(name = "wsImagen.Execute", targetNamespace = "www.aduanas.gub.uy/DAE", partName = "parameters")
        WsImagenExecute parameters);

}
